src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $State = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\Column(length: 255)]
    private ?string $Postal = null;

    #[ORM\Column(length: 255)]
    private ?string $AddressLine1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $AddressLine2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $AddressLine3 = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $AdditionalInformation = null;

    #[ORM\Column(length: 255)]
    private ?string $City = null;
    
    #[ORM\OneToOne(mappedBy: 'Address', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): static
    {
        $this->Country = $Country;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->State;
    }

    public function setState(?string $State): static
    {
        $this->State = $State;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getPostal(): ?string
    {
        return $this->Postal;
    }

    public function setPostal(string $Postal): static
    {
        $this->Postal = $Postal;

        return $this;
    }

    public function getAddressLine1(): ?string
    {
        return $this->AddressLine1;
    }

    public function setAddressLine1(string $AddressLine1): static
    {
        $this->AddressLine1 = $AddressLine1;

        return $this;
    }

    public function getAddressLine2(): ?string
    {
        return $this->AddressLine2;
    }

    public function setAddressLine2(string $AddressLine2): static
    {
        $this->AddressLine2 = $AddressLine2;

        return $this;
    }

    public function getAddressLine3(): ?string
    {
        return $this->AddressLine3;
    }

    public function setAddressLine3(string $AddressLine3): static
    {
        $this->AddressLine3 = $AddressLine3;

        return $this;
    }

    public function getAdditionalInformation(): ?string
    {
        return $this->AdditionalInformation;
    }

    public function setAdditionalInformation(?string $AdditionalInformation): static
    {
        $this->AdditionalInformation = $AdditionalInformation;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): static
    {
        $this->City = $City;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setAddress(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getAddress() !== $this) {
            $user->setAddress($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card implements \App\Entity\Interface\OrderableInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: false)]
    private ?string $name = null;


    #[ORM\ManyToOne(inversedBy: 'cards')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $card_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $card_subtitle = null;

    #[ORM\Column(length: 4095, nullable: true)]
    private ?string $card_body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $card_image = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'shared_cards')]
    #[ORM\JoinTable(name: 'card_shared_with')]
    private Collection $shared_with;

    #[ORM\ManyToOne(inversedBy: 'card', fetch: 'EAGER')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Template $template = null;

    public function __construct()
    {
        $this->shared_with = new ArrayCollection();
    }

    public function getSharedWith(): Collection
    {
        return $this->shared_with;
    }

    public function addSharedWith(User $user): static
    {
        if (!$this->shared_with->contains($user)) {
            $this->shared_with[] = $user;
            $user->getSharedCards()->add($this);
        }

        return $this;
    }

    public function removeSharedWith(User $user): static
    {
        if ($this->shared_with->removeElement($user)) {
            $user->getSharedCards()->removeElement($this);
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCardTitle(): ?string
    {
        return $this->card_title;
    }

    public function setCardTitle(?string $card_title): static
    {
        $this->card_title = $card_title;

        return $this;
    }

    public function getCardSubtitle(): ?string
    {
        return $this->card_subtitle;
    }

    public function setCardSubtitle(?string $card_subtitle): static
    {
        $this->card_subtitle = $card_subtitle;

        return $this;
    }

    public function getCardBody(): ?string
    {
        return $this->card_body;
    }

    public function setCardBody(?string $card_body): static
    {
        $this->card_body = $card_body;

        return $this;
    }

    public function getCardImage(): ?string
    {
        return $this->card_image;
    }

    public function setCardImage(?string $card_image): static
    {
        $this->card_image = $card_image;

        return $this;
    }

    public function getCardImageUrl(): ?string
    {
        if ($this->card_image) {
            return '/uploads/images/' . $this->card_image; // Adjust the path as needed
        }
        return null;
    }

    // ----- CUSTOM METHODS -----

    public function getPrice(): ?int
    {
        $prices = [
            'default' => 500,
            'large' => 750,
        ];

        return $prices[$this->template->getCssClass()] ?? $prices['default'];
    }

    public function toOrderArray(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'author' => $this->author->getUsername(),
            'template' => $this->template->toOrderArray(),
            'card_title' => $this->card_title,
            'card_subtitle' => $this->card_subtitle,
            'card_body' => $this->card_body,
            'card_image' => $this->card_image,
        ];
    }

    public function getOrderLabel(): string
    {
        return $this->name;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): static
    {
        $this->template = $template;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[UniqueEntity(fields: ['email'], message: 'This email is already in use.')]
#[UniqueEntity(fields: ['username'], message: 'This username is already in use.')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    #[ORM\Column(unique: true)]
    private string $username;
    
    #[ORM\Column(unique: true)]
    private string $email;
    #[ORM\Column]
    private string $password;
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var Collection<int, Card>
     */
    #[ORM\ManyToMany(targetEntity: Card::class, mappedBy: 'shared_with')]
    private Collection $shared_cards;

    /**
     * @var Collection<int, Card>
     */
    #[ORM\OneToMany(targetEntity: Card::class, mappedBy: 'author')]
    private Collection $cards;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Address $Address = null;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'user')]
    private Collection $orders;

    /**
     * @var Collection<int, JWT>
     */
    #[ORM\OneToMany(targetEntity: JWT::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $JWTs;

    #[ORM\Column]
    private ?bool $share_cards = false;

    public function __construct()
    {
        $this->shared_cards = new ArrayCollection();
        $this->cards = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->JWTs = new ArrayCollection();
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    // ----- USER INTERFACE METHODS ----- //

    public function eraseCredentials(): void
    {
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getSharedCards(): Collection
    {
        return $this->shared_cards;
    }

    public function addSharedCard(Card $sharedCard): static
    {
        if (!$this->shared_cards->contains($sharedCard)) {
            $this->shared_cards->add($sharedCard);
            $sharedCard->addSharedWith($this);
        }

        return $this;
    }

    public function removeSharedCard(Card $sharedCard): static
    {
        if ($this->shared_cards->removeElement($sharedCard)) {
            $sharedCard->removeSharedWith($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCard(Card $card): static
    {
        if (!$this->cards->contains($card)) {
            $this->cards->add($card);
            $card->setAuthor($this);
        }

        return $this;
    }

    public function removeCard(Card $card): static
    {
        if ($this->cards->removeElement($card)) {
            // set the owning side to null (unless already changed)
            if ($card->getAuthor() === $this) {
                $card->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->Address;
    }

    public function setAddress(?Address $Address): static
    {
        $this->Address = $Address;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, JWT>
     */
    public function getJWTs(): Collection
    {
        return $this->JWTs;
    }

    public function addJWT(JWT $jWT): static
    {
        if (!$this->JWTs->contains($jWT)) {
            $this->JWTs->add($jWT);
            $jWT->setUser($this);
        }

        return $this;
    }

    public function removeJWT(JWT $jWT): static
    {
        if ($this->JWTs->removeElement($jWT)) {
            // set the owning side to null (unless already changed)
            if ($jWT->getUser() === $this) {
                $jWT->setUser(null);
            }
        }

        return $this;
    }

    public function isShareCards(): ?bool
    {
        return $this->share_cards;
    }

    public function setShareCards(bool $share_cards): static
    {
        $this->share_cards = $share_cards;

        return $this;
    }
}

templates/order/cart.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/cart.css') }}">
    {{ parent() }}
{% endblock %}

{% block title %}
    My Cart
{% endblock %}

{% block content %}
<section>
        <div class="columns columns-2">
        <div class="section center-box">
            <h2>My Cart</h2>
            {% if form.orderItems is not empty %}
                {{ form_start(form) }}
                <table class="table table-striped cart-table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Unit Price</th>
                            <th>Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orderItemForm in form.orderItems %}
                            {% set orderItem = orderItemForm.vars.value %} / 100)
                            <tr>
                                <td>
                                    {{ orderItem.label }}
                                </td>
                                <td>
                                    {{ form_widget(orderItemForm.quantity, { 'attr': { 'class': 'table-span' } }) }}
                                </td>
                                <td>
                                    ${{ (orderItem.price / 100)|number_format(2, '.', '') }}
                                </td>
                                <td>
                                    ${{ (orderItem.getTotalPrice() / 100)|number_format(2, '.', '') }}
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="3">Total</td>
                            <td>
                                ${{(order.getTotalPrice() / 100)|number_format(2, '.', '')}}
                            </td>
                    </tbody>
                </table>
                <div class="form-actions">                
                    <a class="button danger" href="{{ path('app_cart_reset') }}">Reset Cart</a>
                    <button type="submit" class="btn btn-primary">Update Cart</button>
                </div>
                {{ form_end(form) }}
            {% else %}
                <p>Your cart is empty.</p>
                <p>You can add items to your cart from your <a href="{{ path('app_card_list') }}">card page</a>.</p>
            {% endif %}
        </div>
        <div class="section center-box">
            <h2>Shipping Address</h2>
            {% if user.address %}
                <p><strong>First Name:</strong> {{ user.address.firstName }}</p>
                <p><strong>Last Name:</strong> {{ user.address.lastName }}</p>
                <p><strong>Country:</strong> {{ user.address.country }}</p>
                {% if user.address.state %}
                    <p><strong>State:</strong> {{ user.address.state }}</p>
                {% endif %}
                <p><strong>City:</strong> {{ user.address.city }}</p>
                <p><strong>Zip Code:</strong> {{ user.address.postal }}</p>
                <p><strong>Street:</strong> <br> {{ user.address.addressLine1 }}
                {% if user.address.addressLine2 %}
                    <br> {{ user.address.addressLine2 }}
                {% endif %}
                {% if user.address.addressLine3 %}
                    <br> {{ user.address.addressLine3 }}
                {% endif %}
                </p>
                {% if user.address.additionalInformation %}
                    <p><strong>Additional Info:</strong> {{ user.address.additionalInformation }}</p>
                {% endif %}
                <a class="button" href="{{ path('app_user_account_edit') }}">Edit Address</a>
            {% else %}
                <p>You need an address to proceed to checkout.</p>
                <a class="button" href="{{ path('app_user_account_edit') }}">Set Address</a>
            {% endif %}
        </div>
        <a class="button success" href="{{ path('app_checkout') }}">Checkout</a>
    </div>
</section>
        
{% endblock %}

templates/order/details.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/cart.css') }}">
        {{ parent() }}
    {% endblock %}

    {% block title %}
        My Cart
    {% endblock %}

    {% block content %}
        <section>
            <div class="section center-box">
                <h2>
                    Your order
                    <em>
                        {{ order.orderNumber }}
                    </em>
                </h2>
                <p>
                    Placed on
                    <em>
                        {{ order.placedAt|date('Y-m-d H:i') }}
                    </em>
                </p>
                <table class="table table-striped cart-table">
                    <thead>
                        <tr>
                            <th>
                                Product
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Unit Price
                            </th>
                            <th>
                                Total Price
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orderItem in order.orderItems %}
                            <tr>
                                <td>
                                    {{ orderItem.label }}
                                </td>
                                <td>
                                    {{ orderItem.quantity }}
                                </td>
                                <td>
                                    ${{ (orderItem.price / 100)|number_format(2, '.', '') }}
                                </td>
                                <td>
                                    ${{ (orderItem.getTotalPrice() / 100)|number_format(2, '.', '') }}
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="3">
                                Total
                            </td>
                            <td>
                                ${{(order.getTotalPrice() / 100)|number_format(2, '.', '')}}
                            </td>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    {% endblock %}
    

templates/order/history.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/order-history.css') }}">
{% endblock %}

{% block content %}
    <section>
        <h1>My Orders</h1>
        {% if orders is empty %}
            <p>You have no orders yet.</p>
        {% else %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Date</th>
                        <th>Total Price</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.orderNumber }}</td>
                            <td>{{ order.placedAt|date('Y-m-d H:i') }}</td>
                            <td>${{ order.getTotalPrice()|number_format(2, '.', '') }}</td>
                            <td>
                                <a href="{{ path('app_order_details', { id: order.id }) }}">View Details</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </section>
{% endblock %}